print ("                 ""Toko Elektronik Gilang")
print ("                ""*************************")
namaPembeli = (input("Masukan Nama Pembeli: "))
kodeAlat = (input("Masukan Kode Alat: "))
hargaAlat = int(input ( "Masukan Harga: "))
jumlahBeli = int(input ("Jumlah Beli: "))
total = hargaAlat * jumlahBeli
print ("     ""===========================")
print ("Nama Pembeli: " +str(namaPembeli))
print ("Kode Alat: "  +str(kodeAlat))
print ("Harga Alat: " +str (hargaAlat))
print ("Jumlah Beli: " +str(jumlahBeli))
print ("Total Harga: " +str(total))